### ISSUE TITLE
dedicated_server_vrack should be idempotent

### ISSUE THREAD

**Issue by balucio** [synthesio/infra-ovh-ansible-module#43]
Hi, firt of all thanks for this Ansible modules.
The module `dedicated_server_vrack` should be idempotent, before set the VRack, it should first check if the the system is in the same VRack, so no error is triggered by OVH Api.

**Comment by xtof-osd** [comment]
In theory, the module does that (test if server already connected to vrack), yet maybe your use-case is not covered. Could you give some precision about it?

**Comment by Skunnyk** [comment]
I confirm, module is looking if dedicated_server is already in the vrack. Can you give us more details ? Maybe another type of servers with unsupported setup :)

**Comment by balucio** [comment]
Sorry, I'm reading now your response. When I try to add a Bare-Methal server to V-Rack, if that server is already added to that v-rack i get an error `Server is already on vRack XXXX`. To avoid this error, first I remove the server from vRack:
```
- name: Removing server from any vRACK
      synthesio.ovh.dedicated_server_vrack:
        service_name: "{{ ovh_service_name }}"
        state: absent
        vrack: "{{ ovh_vracks[item].id }}"
      with_items:
        - 'ovh-main'
        - 'ovh-london'
      loop_control:
        pause: 35
```
Also I need to set a pause foreach removing because sometimes i get an error from OVH API. Then I can add the server on the correct vRack:

```
    - name: Ensure the server is on the correct vRACK
      synthesio.ovh.dedicated_server_vrack:
        service_name: "{{ ovh_service_name }}"
        vrack: "{{ ovh_vracks[_ovh_vrack].id }}"

    - name: Waiting OVH to sync its vRACK after modification
      pause:
        seconds: 35
```
