### ISSUE TITLE
python-ovh

### ISSUE THREAD

**Issue by sisihagen** [synthesio/infra-ovh-ansible-module#49]
I want use the domain module so I install the module. 

My playbook:

```
---
- hosts: localhost
  become: true

  tasks:
    - name: Add server IP to DNS
      synthesio.ovh.domain:
        domain: "sisi-systems.ovh"
        value: "139.99.237.210"
        record_type: "A"
        name: "australia"
```

The error which come:
`msg: python-ovh must be installed to use this module`

The detailed output:

```
ansible-playbook [core 2.12.6]
  config file = /home/siefke/Öffentlich/projects/coding/ansible/ansible.cfg
  configured module search path = ['/home/siefke/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/siefke/.py_ansible/lib/python3.10/site-packages/ansible
  ansible collection location = /home/siefke/.ansible/collections
  executable location = /home/siefke/.py_ansible/bin/ansible-playbook
  python version = 3.10.4 (main, May 14 2022, 05:21:19) [GCC 12.1.0]
  jinja version = 3.1.2
  libyaml = True
Using /home/siefke/Öffentlich/projects/coding/ansible/ansible.cfg as config file
redirecting (type: callback) ansible.builtin.yaml to community.general.yaml
redirecting (type: callback) ansible.builtin.yaml to community.general.yaml
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: ovh_dns.yml 

1 plays in playbooks/service/ovh_dns.yml

PLAY [localhost] 
META: ran handlers

TASK [Add server IP to DNS] 
task path: /home/siefke/Öffentlich/projects/coding/ansible/playbooks/service/ovh_dns.yml:7
fatal: [localhost]: FAILED! => changed=false 
  msg: python-ovh must be installed to use this module
	to retry, use: --limit @/home/siefke/.ansible/retry-files/ovh_dns.retry

PLAY RECAP

localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

The OVH module is installed:

```
pip uninstall ovh
Found existing installation: ovh 0.5.0
Uninstalling ovh-0.5.0:
  Would remove:
    /home/siefke/.py_ansible/lib/python3.10/site-packages/ovh-0.5.0.dist-info/*
    /home/siefke/.py_ansible/lib/python3.10/site-packages/ovh/*
```
