### ISSUE TITLE
Adding a DNS entry does not detect if it previously exists and deletes the current entry.

### ISSUE THREAD

**Issue by dmgweb** [synthesio/infra-ovh-ansible-module#52]
If I run the following playbook both times the subdomain entry is removed:

```
---
- hosts: localhost
  become: true

  tasks:
    - name: Add subdomain xxxx OVH
      synthesio.ovh.domain:
       name: {{ SUBDOMAIN_CREATE }}
       domain: "{{ DOMAIN }}"
       record_type: A
       endpoint: ovh-eu
```

I think it should detect if the entry already exists. If it exists, it should not remove the entry.

In case you want to delete the entry, an argument should be used.

Thanks
