### ISSUE TITLE
BUG: Domain module / DNS - the record is deleted when running it again

### ISSUE THREAD

**Issue by bastianb** [synthesio/infra-ovh-ansible-module#65]
Hi, thank you for provising support for the OVH api!
I want to share a bug with the `synthesio.ovh.domain` task.
Despite being set to default `state: present`, every time the task is run, it either delete the dns record if it exists, or create it if it doesnt not exist. This toggle behavior is not intuitite, not documented and go against the `state` paremeter value.
if I have a `state: present` I expect it to be always created, or only changed if ansible vars are changed (TTL, value...) and not deleted!

Example playbook:
```
---
- name: "Run command from localhost"
  hosts: localhost
  connection: local
  tasks:
    - name: Add DNS entries to OVH
      synthesio.ovh.domain:
        domain: "REDACTED"
        value: "REDACTED"
        record_type: "A"
        name: "test1"
        record_ttl: 120
        state: present

        endpoint: "{{ ovh_endpoint }}"
        application_key: "{{ ovh_application_key }}"
        application_secret: "{{ ovh_application_secret }}"
        consumer_key: "{{ ovh_consumer_key }}"
      tags:
        - ovh
```

the runs:
```
vscode ➜ /workspaces/ansible (main ✗) $ ansible-playbook -i environments/prod/inventory.yaml playbooks/localhost.yaml --tags ovh

PLAY [Run command from localhost] ****************************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Add DNS entries to OVH] ********************************************************************************************************************************************************************************************************************************************************************
changed: [localhost]

PLAY RECAP ***************************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

vscode ➜ /workspaces/ansible (main ✗) $ ansible-playbook -i environments/prod/inventory.yaml playbooks/localhost.yaml --tags ovh

PLAY [Run command from localhost] ****************************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Add DNS entries to OVH] ********************************************************************************************************************************************************************************************************************************************************************
changed: [localhost]

PLAY RECAP ***************************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

vscode ➜ /workspaces/ansible (main ✗) $
```

The first run the domain did not exists hence it created, the second run it deleted the record ! This is not something you want to happend in any environment
