### ISSUE TITLE
Cannot find python-ovh when ansible is installed from distribution and not from pip

### ISSUE THREAD

**Issue by nipil** [synthesio/infra-ovh-ansible-module#96]
I am installing ansible from [PPA](http://ppa.launchpad.net/ansible/ansible/ubuntu) and [infra-ovh-ansible-module](https://github.com/synthesio/infra-ovh-ansible-module) from galaxy. Then creating a virtualenv activating it and installing python ovh. Then i try to use `synthesio.ovh` modules in a playbook, and run ansible.

Problem : ansible is running the synthesio.ovh module with `/usr/bin/python`, as if the activated virtualenv is ignored.

Question : how can i instruct ansible to look for the `python-ovh` dependancy in the virtualenv ?

**Comment by nipil** [comment]
BTW, installing ansible in venv (with python-ovh)  then running ansible from venv solves the problem
But i really want to try and use distribution packages (and at least, find a way to have it work like i wanted)

**Comment by nipil** [comment]
Finally solved my problem with `ansible_python_interpreter`.

Either using vars in a play :

```
---
- name: Play name
  hosts: localhost
  vars:
    ansible_python_interpreter: "{{ lookup('ansible.builtin.env', 'HOME') }}/venv/bin/python3"
```

Or with additional variable as CLI arguments

`-e ansible_python_interpreter=${HOME}/venv/bin/python3`
